apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /   #new 
  name: {{ .Values.kubernetesTests.appName }}
  namespace: {{ .Values.kubernetesTests.namespace }}
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls-secret
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.kubernetesTests.appName }}-service
          servicePort: 80
