apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000