apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: example-app
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: kubernetes-tests
          image: kubernetes-tests:latest # Image to pull
          imagePullPolicy: Never # Only important if the docker image is locally https://medium.com/swlh/how-to-run-locally-built-docker-images-in-kubernetes-b28fbc32cc1d
          ports:
            - containerPort: 5000
