kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: Local
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https